---
name: 'Copy files to/from Azure Blob Container'
author: 'Alex Axthelm'
description: 'Copy files to/from Azure Blob Container using azcopy'
inputs:
  source:
    description: 'Source (to copy)'
    required: true
  destination:
    description: 'Destination (copy to)'
    required: true
  flags:
    description: '(optional) Additional flags to pass to azcopy copy. See README for more information.'
    required: false
runs:
  using: 'composite'
  steps:

    - name: Check for existing `azcopy`
      run: check-for-azcopy.sh
      shell: sh

    - name: Install `azcopy`
      run: install-azcopy.sh
      shell: sh

    - name: Upload results to blob store using azcopy
      env:
        AZCOPY_AUTO_LOGIN_TYPE: AZCLI
        SOURCE: ${{ inputs.source }}
        DESTINATION: ${{ inputs.destination }}
        FLAGS: ${{ inputs.flags }}
      shell: sh
      run: |
        azcopy \
          copy \
          "$SOURCE" \
          "$DESTINATION" \
          "$FLAGS"
