---
name: 'Copy files to/from Azure Blob Container'
author: 'Alex Axthelm'
description: 'Copy files to/from Azure Blob Container using azcopy'
inputs:
  source:
    description: 'Source (to copy)'
    required: true
  destination:
    description: 'Destination (copy to)'
    required: true
  flags:
    description: '(optional) Additional flags to pass to azcopy copy. See README for more information.'
    required: false
  tenant-id:
    description: 'Azure Tenant (same as azure/login)'
    required: true
  client-id:
    description: 'Azure Managed Identity Client ID (same as azure/login)'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Check for existing `azcopy`
      id: azcopy-check
      run: ${{ github.action_path }}/check-for-azcopy.sh
      shell: sh

    - name: Install `azcopy`
      if: ${{ steps.azcopy-check.outputs.azcopy-installed }}
      run: ${{ github.action_path }}/install-azcopy.sh
      shell: sh

    - name: Generate SAS
      uses: azure/CLI@v2
      with:
        # azcliversion: 2.30.0
        inlineScript: |
          end=`date -u -d "5 minutes" '+%Y-%m-%dT%H:%MZ'
          az storage fs directory \
            generate-sas \
            --account-name pactadatadev \
            --name alpha \
            --file-system ghactions-workflow-transition-monitor-results-reports \
            --https-only \
            --permissions dlrw \
            --auth-mode login \
            --expiry $end -o tsv

    - name: Upload results to blob store using azcopy
      env:
        AZCOPY_AUTO_LOGIN_TYPE: AZCLI
        AZCOPY_TENANT_ID: ${{ inputs.tenant-id }}
        DESTINATION: ${{ inputs.destination }}
        FLAGS: ${{ inputs.flags }}
        SOURCE: ${{ inputs.source }}
      shell: sh
      run: |
        azcopy \
          copy \
          "$SOURCE" \
          "$DESTINATION" \
          "$FLAGS"
