---
name: 'Copy files to/from Azure Blob Container'
author: 'Alex Axthelm'
description: 'Copy files to/from Azure Blob Container using azcopy'
inputs:
  source:
    description: 'Source (to copy)'
    required: true
  destination:
    description: 'Destination (copy to)'
    required: true
  overwrite:
    description: 'Overwrite existing files? (default: false)'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # caching pip dependencies
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - name: Install Requirements
      shell: sh
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Copy files
      env:
        SOURCE: ${{ inputs.source }}
        DESTINATION: ${{ inputs.destination }}
      shell: sh
      run: python ${{ github.action_path }}/copy_blob.py
