mime_types = {
    '': {'Description': "Unknown/default", 'mime_type': "application/octet-stream"},
    '.3g2': {'Description': "3GPP2 audio/video container", 'mime_type': "video/3gpp2"},
    '.3gp': {'Description': "3GPP audio/video container", 'mime_type': "video/3gpp"},
    '.7z': {'Description': "7-zip archive", 'mime_type': "application/x-7z-compressed"}
    '.aac': {'Description': "AAC audio", 'mime_type': "audio/aac"},
    '.abw': {'Description': "AbiWord document", 'mime_type': "application/x-abiword"},
    '.apng': {'Description': "Animated Portable Network Graphics (APNG) image", 'mime_type': "image/apng"},
    '.arc': {'Description': "Archive document (multiple files embedded)", 'mime_type': "application/x-freearc"},
    '.avi': {'Description': "AVI: Audio Video Interleave", 'mime_type': "video/x-msvideo"},
    '.avif': {'Description': "AVIF image", 'mime_type': "image/avif"},
    '.azw': {'Description': "Amazon Kindle eBook format", 'mime_type': "application/vnd.amazon.ebook"},
    '.bin': {'Description': "Any kind of binary data", 'mime_type': "application/octet-stream"},
    '.bmp': {'Description': "Windows OS/2 Bitmap Graphics", 'mime_type': "image/bmp"},
    '.bz': {'Description': "BZip archive", 'mime_type': "application/x-bzip"},
    '.bz2': {'Description': "BZip2 archive", 'mime_type': "application/x-bzip2"},
    '.cda': {'Description': "CD audio", 'mime_type': "application/x-cdf"},
    '.csh': {'Description': "C-Shell script", 'mime_type': "application/x-csh"},
    '.css': {'Description': "Cascading Style Sheets (CSS)", 'mime_type': "text/css"},
    '.csv': {'Description': "Comma-separated values (CSV)", 'mime_type': "text/csv"},
    '.doc': {'Description': "Microsoft Word", 'mime_type': "application/msword"},
    '.docx': {'Description': "Microsoft Word (OpenXML)", 'mime_type': "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
    '.eot': {'Description': "MS Embedded OpenType fonts", 'mime_type': "application/vnd.ms-fontobject"},
    '.epub': {'Description': "Electronic publication (EPUB)", 'mime_type': "application/epub+zip"},
    '.gif': {'Description': "Graphics Interchange Format (GIF)", 'mime_type': "image/gif"},
    '.gz': {'Description': "GZip Compressed Archive", 'mime_type': "application/gzip."},
    '.htm': {'Description': "HyperText Markup Language (HTML)", 'mime_type': "text/html"},
    '.html': {'Description': "HyperText Markup Language (HTML)", 'mime_type': "text/html"},
    '.ico': {'Description': "Icon format", 'mime_type': "image/vnd.microsoft.icon"},
    '.ics': {'Description': "iCalendar format", 'mime_type': "text/calendar"},
    '.jar': {'Description': "Java Archive (JAR)", 'mime_type': "application/java-archive"},
    '.jpeg': {'Description': "JPEG images", 'mime_type': "image/jpeg"},
    '.jpg': {'Description': "JPEG images", 'mime_type': "image/jpeg"},
    '.js': {'Description': "JavaScript", 'mime_type': "text/javascript"},
    '.json': {'Description': "JSON format", 'mime_type': "application/json"},
    '.jsonld': {'Description': "JSON-LD format", 'mime_type': "application/ld+json"},
    '.mid': {'Description': "Musical Instrument Digital Interface (MIDI)", 'mime_type': "audio/midi, audio/x-midi"},
    '.midi': {'Description': "Musical Instrument Digital Interface (MIDI)", 'mime_type': "audio/midi, audio/x-midi"},
    '.mjs': {'Description': "JavaScript module", 'mime_type': "text/javascript"},
    '.mp3': {'Description': "MP3 audio", 'mime_type': "audio/mpeg"},
    '.mp4': {'Description': "MP4 video", 'mime_type': "video/mp4"},
    '.mpeg': {'Description': "MPEG Video", 'mime_type': "video/mpeg"},
    '.mpkg': {'Description': "Apple Installer Package", 'mime_type': "application/vnd.apple.installer+xml"},
    '.odp': {'Description': "OpenDocument presentation document", 'mime_type': "application/vnd.oasis.opendocument.presentation"},
    '.ods': {'Description': "OpenDocument spreadsheet document", 'mime_type': "application/vnd.oasis.opendocument.spreadsheet"},
    '.odt': {'Description': "OpenDocument text document", 'mime_type': "application/vnd.oasis.opendocument.text"},
    '.oga': {'Description': "Ogg audio", 'mime_type': "audio/ogg"},
    '.ogv': {'Description': "Ogg video", 'mime_type': "video/ogg"},
    '.ogx': {'Description': "Ogg", 'mime_type': "application/ogg"},
    '.opus': {'Description': "Opus audio in Ogg container", 'mime_type': "audio/ogg"},
    '.otf': {'Description': "OpenType font", 'mime_type': "font/otf"},
    '.pdf': {'Description': "Adobe Portable Document Format (PDF)", 'mime_type': "application/pdf"},
    '.php': {'Description': "Hypertext Preprocessor (Personal Home Page)", 'mime_type': "application/x-httpd-php"},
    '.png': {'Description': "Portable Network Graphics", 'mime_type': "image/png"},
    '.ppt': {'Description': "Microsoft PowerPoint", 'mime_type': "application/vnd.ms-powerpoint"},
    '.pptx': {'Description': "Microsoft PowerPoint (OpenXML)", 'mime_type': "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
    '.rar': {'Description': "RAR archive", 'mime_type': "application/vnd.rar"},
    '.rtf': {'Description': "Rich Text Format (RTF)", 'mime_type': "application/rtf"},
    '.sh': {'Description': "Bourne shell script", 'mime_type': "application/x-sh"},
    '.svg': {'Description': "Scalable Vector Graphics (SVG)", 'mime_type': "image/svg+xml"},
    '.tar': {'Description': "Tape Archive (TAR)", 'mime_type': "application/x-tar"},
    '.tif': {'Description': "Tagged Image File Format (TIFF)", 'mime_type': "image/tiff"},
    '.tiff': {'Description': "Tagged Image File Format (TIFF)", 'mime_type': "image/tiff"},
    '.ts': {'Description': "MPEG transport stream", 'mime_type': "video/mp2t"},
    '.ttf': {'Description': "TrueType Font", 'mime_type': "font/ttf"},
    '.txt': {'Description': "Text, (generally ASCII or ISO 8859-n)", 'mime_type': "text/plain"},
    '.vsd': {'Description': "Microsoft Visio", 'mime_type': "application/vnd.visio"},
    '.wav': {'Description': "Waveform Audio Format", 'mime_type': "audio/wav"},
    '.weba': {'Description': "WEBM audio", 'mime_type': "audio/webm"},
    '.webm': {'Description': "WEBM video", 'mime_type': "video/webm"},
    '.webp': {'Description': "WEBP image", 'mime_type': "image/webp"},
    '.woff': {'Description': "Web Open Font Format (WOFF)", 'mime_type': "font/woff"},
    '.woff2': {'Description': "Web Open Font Format (WOFF)", 'mime_type': "font/woff2"},
    '.xhtml': {'Description': "XHTML", 'mime_type': "application/xhtml+xml"},
    '.xls': {'Description': "Microsoft Excel", 'mime_type': "application/vnd.ms-excel"},
    '.xlsx': {'Description': "Microsoft Excel (OpenXML)", 'mime_type': "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
    '.xml': {'Description': "XML", 'mime_type': "application/xml"},
    '.xul': {'Description': "XUL", 'mime_type': "application/vnd.mozilla.xul+xml"},
    '.zip': {'Description': "ZIP archive", 'mime_type': "application/zip"},
    None: {'Description': "Unknown/default", 'mime_type': "application/octet-stream"},
}
