---
on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: "prefix for artifacts containing JSON to be included in comment"
        type: string
        required: false
        default: "comment-json-"
      header:
        description: 'Header text for comment'
        required: true
        type: string



jobs:
  add_comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Read new JSON
        id: json-read
        uses: actions/download-artifact@v4
        with:
          path: /tmp/comment-json
          pattern: ${{ inputs.artifact-prefix }}*
          merge-multiple: true

      - name: Merge new JSON
        id: json-merge
        run: |
          ls -laR /tmp/comment-json
          NEW_JSON=$(jq -sc '.' /tmp/comment-json/*.json)
          echo "NEW_JSON=$NEW_JSON"
          echo "NEW_JSON=$NEW_JSON" >> $GITHUB_ENV

      - name: Create markdown table
        uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: "${{ env.NEW_JSON }}"
      - run: echo "${{ steps.table.outputs.table }}"

      - name: Find Comment
        # https://github.com/peter-evans/find-comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ${{ inputs.header }}

      - name: Extract old JSON
        run: |
          echo "${{ steps.fc.outputs.comment-body }}" >> history.md
          history_json=$(grep "History JSON" history.md | grep -o '\[.*\]')
          echo $history_json
          echo $history_json >> history_json.json
          echo ${{ env.NEW_JSON }} >> new_json.json
          HISTORY_JSON=$(jq -sc '.' new_json.json history_json.json)
          echo "HISTORY_JSON=$HISTORY_JSON"
          echo "HISTORY_JSON=$HISTORY_JSON" >> $GITHUB_ENV

      - name: Create history markdown table
        uses: buildingcash/json-to-markdown-table-action@v1
        id: table-history
        with:
          json: "${{ env.HISTORY_JSON }}"
      - run: echo "${{ steps.table-history.outputs.table }}"

      - name: Create or update comment
        # https://github.com/peter-evans/create-or-update-comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # ${{ inputs.header }}
            ${{ steps.table.outputs.table }}
            <details>
              <summary>History</summary>

              ${{ steps.table-history.outputs.table }}

              <details><summary>History JSON</summary>`${{ env.HISTORY_JSON }}`</details>
            </details>
          edit-mode: replace
