---
on:
  workflow_call:
    inputs:
      fetch-depth:
        description: 'fetch-depth for checkout (default: 0, get entire history). 2 retrieves preceeding commit.'
        required: false
        default: 0
        type: number
      files:
        description: 'File paths to check for changes'
        required: true
        type: string
      base_sha:
        description: 'Base SHA to use for comparison'
        required: false
        type: string
        default: |
          ${{
            github.event_name == 'pull_request' && github.event.pull_request.base.sha ||
            github.event_name == 'push' && github.event.push.before ||
            ''
          }}
    outputs:
      any_changed:
        description: "true/false if any files named in `files` input have changed"
        value: ${{ jobs.updated-files.outputs.any_changed }}
      all_modified_files:
        description: "list of all modified files"
        value: ${{ jobs.updated-files.outputs.all_modified_files }}

name: Check for updated R files

jobs:
  updated-files:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ github.token }}
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_modified_files: ${{ steps.changed-files.outputs.all_modified_files }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          base_sha: ${{ inputs.base_sha }}
          # Avoid using single or double quotes for multiline patterns
          files: ${{ inputs.files }}

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
