---
name: Docker

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Path to Dockerfile'
        required: false
        default: 'Dockerfile'
        type: string
      image-name:
        description: 'Name for docker image (default: full repository name)'
        required: false
        default: ${{ github.repository }}
        type: string
      build-platform:
        description: platforms to build docker image on
        required: false
        type: string
        default: |
          ${{
            github.event_name == 'pull_request' && '["linux/amd64"]' ||
            '[
              "linux/amd64",
              "linux/arm64"
            ]'
          }}
      do-lint:
        description: 'Flag to lint Dockerfile'
        required: false
        default: true
        type: boolean
      do-build-and-push:
        description: 'Flag to Build and push docker image to GitHub packages'
        required: false
        default: true
        type: boolean
      do-check-r-sysdeps:
        description: 'Flag to Build and push docker image to GitHub packages'
        required: false
        default: true
        type: boolean
    outputs:
      full-image-name:
        description: "Full pushed image name including host/registry, name, and tag"
        value: ${{ jobs.build-docker-image.outputs.full-image-name }}


jobs:

  hadolint:
    if: ${{ inputs.do-lint }}
    uses: ./.github/workflows/docker-hadolint.yml
    with:
      dockerfile: ${{ inputs.dockerfile }}

  build-docker-image:
    if: ${{ inputs.do-build-and-push }}
    uses: ./.github/workflows/docker-build-multiarch.yml
    secrets: inherit
    with:
      image-name: ${{ inputs.image-name }}
      build-platform: ${{ inputs.build-platform }}

  check-r-sysdeps:
    if: ${{ inputs.do-check-r-sysdeps }}
    uses: ./.github/workflows/docker-check-R-sysdeps.yml
    needs: [build-docker-image]
    with:
      image: ${{needs.build-docker-image.outputs.full-image-name}}

  add-comment:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/add-comment-table.yml
    needs: [build-docker-image]
    with:
      header: "Docker build status"
