---
name: General Checks
on:
  workflow_call:

jobs:
  megalinter:
    uses:
      ./.github/workflows/General-mega-linter.yaml

  superLinter:
    uses:
      ./.github/workflows/General-super-linter.yml
