on:
  workflow_call:

name: Sync GitHub Issues to Azure DevOps 

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.2
        id: gh_to_ado
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}" 
          github_token: "${{ secrets.REPO_PAT }}"
          ado_organization: "RMI-PACTA"
          ado_project: "2DegreesInvesting"
          ado_area_path: "2DegreesInvesting\\Test Team 1"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Committed"
          ado_close_state: "Done" 
          log_level: 100
  add_comment:
    needs: alert
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        # https://github.com/peter-evans/find-comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ADO ticket

      - name: Create or update comment
        # https://github.com/peter-evans/create-or-update-comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ADO ticket automatically created for this issue: (${{ steps.gh_to_ado.id }})
          edit-mode: replace
