---
name: GH issues
on:
  workflow_call:
    inputs:
      do-gh-to-ado:
        description: 'Flag to run `gh-to-ado`'
        required: false
        default: true
        type: boolean
      ado_area_path:
        description: 'ADO area path where ADO tickets should be created'
        required: true
        default: true
        type: string

jobs:
  gh-to-ado:
    if: ${{ inputs.do-gh-to-ado }}
    uses: ./.github/workflows/issues-gh-to-ado.yml
    secrets: inherit
