on:
  workflow_call:

name: Sync GitHub Issues to Azure DevOps 

jobs:
  alert:
    if: ${{ (!github.event.issue.pull_request) && (github.event.label.name == 'ADO' )}}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.2
        id: gh_to_ado
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}" 
          github_token: "${{ secrets.GH_TO_ADO_PAT }}"
          ado_organization: "RMI-PACTA"
          ado_project: "2DegreesInvesting"
          ado_area_path: "2DegreesInvesting\\Test Team 1"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Committed"
          ado_close_state: "Done" 
          log_level: 100
