on:
  workflow_call:
    inputs:
      ado_area_path:
        description: "ADO area path where ADO tickets are created."
        required: true
        default: "2DegreesInvesting\\GitHub Issues"
        type: string
    secrets:
      ADO_TOKEN:
        description: "ADO personal access token"
        required: true
name: Sync GitHub Issues to Azure DevOps 

jobs:
  alert:
    if: ${{ (!github.event.issue.pull_request) && (github.event.label.name == 'ADO' )}}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.3
        id: gh_to_ado
        env:
          ado_token: "${{ secrets.ADO_TOKEN }}" 
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          ado_organization: "RMI-PACTA"
          ado_project: "2DegreesInvesting"
          ado_area_path: "${{ inputs.ado_area_path }}"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Committed"
          ado_close_state: "Done" 
          log_level: 100
