---
name: GH issues
on:
  workflow_call:
    inputs:
      do-gh-to-ado:
        description: 'Flag to run `gh-to-ado`'
        required: false
        default: true
        type: boolean

jobs:
  gh-to-ado:
    if: ${{ inputs.do-gh-to-ado }}
    uses: ./.github/workflows/issues-gh-to-ado.yml
    with:
      ado_area_path: "2DegreesInvesting\\Test Team 1"
    secrets:
      ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}" 
      github_token: "${{ secrets.GH_TO_ADO_PAT }}"
