---
name: R Package Checks
on:
  workflow_call:

jobs:
  R-CMD-check:
    uses:
      ./.github/workflows/R-CMD-check.yml

  lintr:
    uses:
      ./.github/workflows/R-lint.yml

  test-coverage:
    name: Code Coverage
    uses:
      ./.github/workflows/R-test-coverage.yml
