---
on:
  workflow_call:

name: Version check

jobs:
  version-check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ github.token }}
    permissions:
      pull-requests: read

    steps:

      - name: Get all changed R package files
        id: changed-package-files
        uses: tj-actions/changed-files@v42
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.R
             DESCRIPTION
             LICENSE
             LICENSE.md
             NAMESPACE
             R/**
             data/**
             inst/**
             src/**
             vignettes/**

      - name: No changed R files
        if: steps.changed-package-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-package-files.outputs.all_changed_files }}
        run: |
          echo "No Changed R files."
          echo "Files changed in this PR:"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
          done

      - name: checkout working HEAD
        if: steps.changed-package-files.outputs.any_changed == 'false'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          sparse-checkout: |
            DESCRIPTION
          path: working

      - name: checkout base HEAD
        if: steps.changed-package-files.outputs.any_changed == 'false'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          sparse-checkout: |
            DESCRIPTION
          path: compare

      - name: show files
        if: steps.changed-package-files.outputs.any_changed == 'false'
        run: |
          ls -lR working compare
          echo "\nWORKING:\n"
          cat working/DESCRIPTION
          echo "\nCOMPARE:\n"
          cat compare/DESCRIPTION

      - name: Setup R
        if: steps.changed-package-files.outputs.any_changed == 'false'
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: compare versions
        if: steps.changed-package-files.outputs.any_changed == 'false'
        run: |
          Rscript -e " \
            install.packages('desc'); \
            working_version <- desc::desc_get_version('working/DESCRIPTION'); \
            message('working version: ', working_version); \
            compare_version <- desc::desc_get_version('compare/DESCRIPTION'); \
            message('compare version: ', compare_version); \
            stopifnot(working_version > compare_version); \
          "
