---
name: R
on:
  workflow_call:
    inputs:
      do-lint:
        description: 'Flag to run `lintr`'
        required: false
        default: true
        type: boolean


jobs:

  lintr:
    if: ${{ inputs.do-lint }}
    uses: ./.github/workflows/R-lintr.yml
