---
name: R
on:
  workflow_call:
    inputs:
      do-r-cmd-check:
        description: 'Flag to run `R CMD CHECK`'
        required: false
        default: true
        type: boolean
      do-lint:
        description: 'Flag to run `lintr`'
        required: false
        default: true
        type: boolean
      do-codecov:
        description: 'Flag to check codecoverage and upload to codecov.io'
        required: false
        default: true
        type: boolean
      do-compare-versions:
        description: 'Flag to compare versions in DESCRIPTION'
        required: false
        default: true
        type: boolean
      do-docs-check:
        description: 'Flag to check documentation is up to date'
        required: false
        default: true
        type: boolean
      r-cmd-check-error-on:
        description: 'Level of R CMD CHECK issue to fail check'
        required: false
        default: '"note"'
        type: string


jobs:

  lintr:
    if: ${{ inputs.do-lint }}
    uses: ./.github/workflows/R-lintr.yml

  codecov:
    if: ${{ inputs.do-codecov }}
    uses: ./.github/workflows/R-codecov.yml

  r-cmd-check:
    if: ${{ inputs.do-r-cmd-check }}
    uses: ./.github/workflows/R-CMD-check.yml
    with:
      error-on: ${{ inputs.r-cmd-check-error-on }}

  version-check:
    if: ${{ inputs.do-compare-versions }}
    uses: ./.github/workflows/R-semver-check.yml

  docs-check:
    if: ${{ inputs.do-docs-check }}
    uses: ./.github/workflows/R-check-docs.yml